### ISSUE TITLE
C stack usage  7970016 is too close to the limit

### ISSUE THREAD

**Issue by angelesdecara** [ekirving/qpbrute#4]
Dear Evan,

A little hand accidentally closed my laptop lid, and when I try to restart the calculation of the Bayes factors, I get this message:

INFO: There are 784 graphs to compute Bayes factors for.
INFO: Bayes factor done for graph 204a55b
Traceback (most recent call last):
  File "qpbayes.py", line 223, in <module>
    calculate_bayes_factors(argv.geno, argv.snp, argv.ind, argv.prefix, argv.pops, argv.out, nthreads=argv.threads)
  File "qpbayes.py", line 201, in calculate_bayes_factors
    qpb.calculate_bayes_factors()
  File "qpbayes.py", line 154, in calculate_bayes_factors
    self.model_likelihood(graph)
  File "qpbayes.py", line 172, in model_likelihood
    MCMC_NUM_BURN], env={'OMP_NUM_THREADS': '1'}, stdout=open(log_file, 'w'))
  File "/Users/angeles/Downloads/qpbrute/utils.py", line 50, in run_cmd
    raise RuntimeError(err)
RuntimeError: Registered S3 methods overwritten by 'ggplot2':
  method         from 
  [.quosures     rlang
  c.quosures     rlang
  print.quosures rlang
Something went wrong, trying again.
Error: C stack usage  7970016 is too close to the limit
Execution halted

Any clue what's going on?
Many thanks,

Angeles

**Comment by ekirving** [comment]
That error is caused by R trying to access more system resources than your operating system allows by default.

This answer on Stack Overflow shows how you can permanently increase the `ulimit` in OS X https://unix.stackexchange.com/questions/108174/how-to-persistently-control-maximum-system-resource-consumption-on-mac#answer-221988

However, it might make more sense to run the Bayes Factor calculations on a linux server, rather than on your laptop. The code will run to completion on OS X (provided systems limits are increased), but for non-trivial datasets each model can take > 1 week to complete.
